# Site settings
title: Kurdish Computational Linguistics Course
subtitle: Natural Language Processing and Computational Linguistics in Kurdish
#description: |
baseurl: "/KurdishCL" # the subpath of your site, e.g. /blog/
url: "https://sinaahmadi.github.io" # the base hostname & protocol for your site
syllabus: ""
githubdir: "sinaahmadi/KurdishCL "

# Author/user information
email: ahmadi.sina@outlook.com
twitter_username: sina_ahm
github_username:  sinaahmadi
authorurl: "https://sinaahmadi.github.io/"
#address: |
#    Online


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
